### ISSUE TITLE
Better webhook regex

### ISSUE THREAD

**Issue by IlluminatiFish** [notLeeter/anti-session-stealer#1]
``(?P<scheme>https?):\/\/(?P<domain>(?:ptb\.|canary\.)?discord(?:app)?\.com)\/api(?:\/)?(?P<api_version>v\d{1,2})?\/webhooks\/(?P<webhook_identifier>\d{17,19})\/(?P<webhook_token>[\w\-]{68})``

**Comment by notLeeter** [comment]
I have now changed the regex used in the scripts to the one you have provided, thank you!
https://github.com/notLeeter/anti-session-stealer/commit/486b062d0625717bd16b81030b8e1fdafe9174fa
